In [1]:
import numpy

In [2]:
L1=numpy.random.randn(5)

In [3]:
L1

array([-1.34377328, -0.06965053,  0.44777577, -1.61771984,  2.03643124])

array([-1.34377328, -0.06965053,  0.44777577, -1.61771984,  2.03643124])

In [4]:
L2=numpy.where(L1>0,1,0)

In [5]:
data=numpy.stack((L1,L2),axis=1)

In [6]:
data

array([[-1.34377328,  0.        ],
       [-0.06965053,  0.        ],
       [ 0.44777577,  1.        ],
       [-1.61771984,  0.        ],
       [ 2.03643124,  1.        ]])

array([[-1.34377328,  0.        ],
       [-0.06965053,  0.        ],
       [ 0.44777577,  1.        ],
       [-1.61771984,  0.        ],
       [ 2.03643124,  1.        ]])

In [7]:
import torch
from torch import nn
loss=nn.BCELoss()

In [8]:
input=torch.autograd.Variable(torch.Tensor(data[:,0].reshape((5,1))),requires_grad=True)
input

Variable containing:
-1.3438
-0.0697
 0.4478
-1.6177
 2.0364
[torch.FloatTensor of size 5x1]

Variable containing:
-1.3438
-0.0697
 0.4478
-1.6177
 2.0364
[torch.FloatTensor of size 5x1]

In [9]:
target=torch.autograd.Variable(torch.Tensor(data[:,1].reshape((5,1))))
target

Variable containing:
 0
 0
 1
 0
 1
[torch.FloatTensor of size 5x1]

Variable containing:
 0
 0
 1
 0
 1
[torch.FloatTensor of size 5x1]

In [10]:
from torch.autograd import Variable
model=torch.nn.Sequential(
    torch.nn.Linear(1,10),
    torch.nn.ReLU(),
    torch.nn.Linear(10,5),
    torch.nn.ReLU(),
    torch.nn.Linear(5,1),
    torch.nn.ReLU(),
)

In [11]:
model

Sequential (
  (0): Linear (1 -> 10)
  (1): ReLU ()
  (2): Linear (10 -> 5)
  (3): ReLU ()
  (4): Linear (5 -> 1)
  (5): ReLU ()
)

Sequential (
  (0): Linear (1 -> 10)
  (1): ReLU ()
  (2): Linear (10 -> 5)
  (3): ReLU ()
  (4): Linear (5 -> 1)
  (5): ReLU ()
)

In [12]:
ll=loss(model(input),target)

In [13]:
ll

Variable containing:
 0.6096
[torch.FloatTensor of size 1]

Variable containing:
 0.6096
[torch.FloatTensor of size 1]

In [14]:
model.zero_grad()

In [15]:
ll.backward()

In [16]:
for param in model.parameters():
    param.data-=0.1*param.grad.data

In [17]:
for param in model.parameters():
    print(param.data)


 0.4157
-0.6576
-0.0743
-0.5134
-0.2488
 0.2722
-0.9457
 0.2895
 0.4665
 0.6346
[torch.FloatTensor of size 10x1]


 0.2622
 0.1146
 0.9324
 0.4220
 0.1945
-0.1823
-0.2711
 0.8837
 0.4338
 0.1053
[torch.FloatTensor of size 10]


-0.2573  0.2353 -0.2236 -0.2860  0.2243 -0.1043 -0.2069  0.3070  0.2336  0.2636
-0.3052 -0.3041 -0.0735 -0.2405 -0.2780 -0.1895  0.2566  0.1217 -0.2519  0.2310
 0.0221  0.2752 -0.0777 -0.0242  0.0884  0.1698 -0.0344 -0.2683 -0.1254 -0.2869
 0.0715 -0.1303  0.2031 -0.2952  0.2014 -0.1408 -0.2876 -0.0882  0.2073 -0.2237
-0.0413 -0.3089 -0.0899 -0.2780  0.0435  0.0446 -0.2160 -0.0610 -0.0517 -0.1149
[torch.FloatTensor of size 5x10]


-0.0329
-0.3046
 0.0206
 0.1306
-0.2027
[torch.FloatTensor of size 5]


 0.2601  0.2503  0.0817  0.2881  0.4407
[torch.FloatTensor of size 1x5]


 0.3524
[torch.FloatTensor of size 1]


 0.4157
-0.6576
-0.0743
-0.5134
-0.2488
 0.2722
-0.9457
 0.2895
 0.4665
 0.6346
[torch.FloatTensor of size 10x1]


 0.2622
 0.1146
 0.9324
 0.4220
 0.