In [1]:
import numpy

In [7]:
a=numpy.array(range(20)).reshape(5,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
a.dot(a.T)

array([[  14,   38,   62,   86,  110],
       [  38,  126,  214,  302,  390],
       [  62,  214,  366,  518,  670],
       [  86,  302,  518,  734,  950],
       [ 110,  390,  670,  950, 1230]])

In [12]:
numpy.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
b=a[:4];b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
numpy.linalg.inv(b)

LinAlgError: Singular matrix

In [19]:
numpy.linalg.inv(_12)

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.33333333]])

In [19]:
a=numpy.random.uniform(size=(5,5))

In [20]:
a

array([[ 0.48785588,  0.82095088,  0.15905156,  0.32532849,  0.58271028],
       [ 0.89645323,  0.27571171,  0.39984303,  0.45202767,  0.82124254],
       [ 0.45574378,  0.42110598,  0.3333011 ,  0.26751711,  0.89462926],
       [ 0.53432326,  0.30799752,  0.08149774,  0.88247812,  0.15213033],
       [ 0.99608113,  0.43806056,  0.93113134,  0.5576325 ,  0.93732604]])

In [23]:
n1=a-numpy.array([1,10,100,1000,10000])

In [24]:
n1.min(axis=0)

array([ -5.44256225e-01,  -9.72428829e+00,  -9.99185023e+01,
        -9.99732483e+02,  -9.99984787e+03])

In [26]:
n2=n1/numpy.array([2,20,200,2000,20000])

In [27]:
n2

array([[-0.25607206, -0.45895246, -0.49920474, -0.49983734, -0.49997086],
       [-0.05177339, -0.48621441, -0.49800078, -0.49977399, -0.49995894],
       [-0.27212811, -0.4789447 , -0.49833349, -0.49986624, -0.49995527],
       [-0.23283837, -0.48460012, -0.49959251, -0.49955876, -0.49999239],
       [-0.00195944, -0.47809697, -0.49534434, -0.49972118, -0.49995313]])